baseURL = "https://xpsychometrics.github.io/"
languageCode = "en-us"
title = "XPsychometrics Research Lab"
theme = "academic"

[params]
  description = "XPsychometrics Research Lab - Advancing Psychological Measurement and Quantitative Methods"
  logo = "images/logo.png"
  organization = "XPsychometrics Research Lab"
  organization_logo = "images/logo.png"

[menu]
  [[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 10
  [[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 20
  [[menu.main]]
    name = "Team"
    url = "/team/"
    weight = 30
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 40
