baseURL = "https://xpsychometrics.github.io/"
languageCode = "en-us"
title = "xPsychometrics Research Lab"
theme = "academic"

[params]
  description = "Research in psychometrics and quantitative methods"
  keywords = ["psychometrics", "research", "statistics", "methodology"]
  copyright = "© 2025 xPsychometrics Research Lab"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 2
  [[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 3
  [[menu.main]]
    name = "Team"
    url = "/team/"
    weight = 4
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5
